version: '3.7'
services:
  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
  solr:
    image: solr:9.3
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181
    depends_on:
      - zoo1