version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - TIKA_URL=http://ayd-tika-1:9998
      - SOLR_URL=http://ayd-solr-1:8983
      - ZK_URLS=http://ayd-zoo1-1:2181
      - BACKEND_URL=http://ayd-backend-1:8000
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - solr
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - solr
  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
  solr:
    image: solr:9.3
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo1:2181
    depends_on:
      - zoo1