---

roles:
  - name: smc40_monitoring_project
    src: https://github.com/smc40/smc-bit-monitoring.git
  - name: smc40_docker
    src: https://github.com/smc40/dori-deploy.git
  - name: smc40_pki
    src: https://github.com/smc40/dori-deploy.git

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.postgresql
  - name: ericsysmin.docker
  - name: manala.roles
