---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.postgresql
  - name: ericsysmin.docker
  - name: manala.roles
  - name: https://github.com/smc40/ansible-bit.git
    type: git
    version: master
